[global]
gmCapable               1
priority1               127
priority2               128
logSyncInterval         -3
syncReceiptTimeout      3
neighborPropDelayThresh 800
min_neighbor_prop_delay -20000000
assume_two_step         1
path_trace_enabled      1

# gPTP Requirements
network_transport       L2
delay_mechanism         P2P
transportSpecific       0x1

[enP8p1s0]
