# config/prop_controllers.yaml

# Publish joint states at 50 Hz so LiftDragPlugin can read velocities
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# One controller for all four props
joint_motor_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - front_right_prop_joint
    - front_left_prop_joint
    - rear_left_prop_joint
    - rear_right_prop_joint
  # By default it listens on /<controller_name>/command,
  # so no need to override unless you want a different topic.
  # command_topic: /motor_speed
  state_publish_rate: 50
  constraints:
    max_velocity:     2000   # rad/s
    max_acceleration: 10000  # rad/s²
